version: '3.8'

services:
  # The PostgreSQL Database Container
  db:
    image: postgres:15
    container_name: bess_postgres_container
    restart: always
    environment:
      POSTGRES_DB: bess_db
      POSTGRES_USER: nikos_admin
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: